---
title: Appunti
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.12.0
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## Tirocini di ricerca

#### Tirocinio M2 @ LPENS
- [Hamiltonian truncation in long-range one-dimensional CFTs (relazione)](/doc/M2 report.pdf) - 2025
- [Hamiltonian truncation in long-range one-dimensional CFTs (presentazione)](/doc/M2 slides.pdf) - 2025

#### Tirocinio M1 @ University of Turin, Department of Physics
- [Conformal Defects in Nonlocal O(N )-invariant Theories (relazione)](/doc/M1 report.pdf) - 2024
- [Conformal Defects in Nonlocal O(N )-invariant Theories (presentazione)](/doc/M1 slides.pdf) - 2024

#### Tirocinio di ricerca @ Inria Paris & Centre Automatique et Systèmes - Mines Paris
- [Laying the Groundwork for Tensor Network Approaches to Lattice Yang-Mills Theory](/doc/Inria internship.pdf) - 2023

#### Tirocinio di ricerca @ Oxford University, Department of Engineering Science
- [Nuclear spin control in GaAs quantum dots via nuclear quadrupole resonance](/doc/Oxford internship.pdf) - 2023
- [Poster conferenza @ QUEST 2023 a Parigi](/doc/Oxford poster.pdf) - 2023

## Progetti

#### Progetto bibliografico ENS M2 CFT
- [Defect conformal field theory](/doc/DCFT project.pdf) - 2025

#### Progetto bibliografico ENS M1
- [Conformal field theory and the long-range Ising Model (relazione)](/doc/Bibliographical project.pdf) - 2024
- [Conformal field theory and the long-range Ising Model (presentazione)](/doc/Bibliographical project slides.pdf) - 2024

## Varie

- [One-loop renormalization of gauge theory](/doc/QFT2.pdf) - 2025


